"""Make residue expires_at nullable

Revision ID: 6d786bcad2e8
Revises: b7c8d9e0f1a2
Create Date: 2025-12-28 09:31:51.436801

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6d786bcad2e8'
down_revision = 'b7c8d9e0f1a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ecm_residues', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # Clear expires_at on available residues (they no longer expire by time)
    # Only claimed residues should have expires_at set
    op.execute("""
        UPDATE ecm_residues
        SET expires_at = NULL
        WHERE status = 'available'
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Set a default expires_at for residues that have NULL
    op.execute("""
        UPDATE ecm_residues
        SET expires_at = created_at + INTERVAL '7 days'
        WHERE expires_at IS NULL
    """)

    op.alter_column('ecm_residues', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###