"""Add current_composite, has_snfs_form, and snfs_difficulty to composites

Revision ID: d11887201647
Revises: 005_add_client_ip
Create Date: 2025-09-30 12:55:42.270183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd11887201647'
down_revision = '005_add_client_ip'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns as nullable first
    op.add_column('composites', sa.Column('current_composite', sa.Text(), nullable=True))
    op.add_column('composites', sa.Column('has_snfs_form', sa.Boolean(), nullable=True))
    op.add_column('composites', sa.Column('snfs_difficulty', sa.Integer(), nullable=True))

    # Populate current_composite with existing number values
    op.execute("UPDATE composites SET current_composite = number WHERE current_composite IS NULL")

    # Set has_snfs_form default to false for existing records
    op.execute("UPDATE composites SET has_snfs_form = false WHERE has_snfs_form IS NULL")

    # Make columns non-nullable now that they have values
    op.alter_column('composites', 'current_composite', nullable=False)
    op.alter_column('composites', 'has_snfs_form', nullable=False)

    op.drop_index('ix_composites_priority', table_name='composites')
    op.create_index(op.f('ix_composites_priority'), 'composites', ['priority'], unique=False)
    op.create_index('ix_composites_priority_work', 'composites', ['priority', 'is_fully_factored'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_composites_priority_work', table_name='composites')
    op.drop_index(op.f('ix_composites_priority'), table_name='composites')
    op.create_index('ix_composites_priority', 'composites', ['priority', 'is_fully_factored'], unique=False)
    op.drop_column('composites', 'snfs_difficulty')
    op.drop_column('composites', 'has_snfs_form')
    op.drop_column('composites', 'current_composite')
    # ### end Alembic commands ###