"""add is_active to composites

Revision ID: fea6b9ad9060
Revises: a1b2c3d4e5f6
Create Date: 2025-11-25 14:35:41.801187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fea6b9ad9060'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add is_active column with default False for new composites
    op.add_column('composites', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='false'))

    # Data migration: Set all existing composites to active=true
    # This ensures existing composites continue to be available for work assignment
    op.execute("UPDATE composites SET is_active = true")

    # Add indexes for query performance
    op.create_index('ix_composites_active_status', 'composites', ['is_active', 'is_fully_factored'], unique=False)
    op.create_index(op.f('ix_composites_is_active'), 'composites', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_composites_is_active'), table_name='composites')
    op.drop_index('ix_composites_active_status', table_name='composites')
    op.drop_column('composites', 'is_active')
    # ### end Alembic commands ###